project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('studies.urls')),
]

studies/urls.py
from django.urls import path

from . import views

app_name = 'studies'

urlpatterns = [
    path('', views.home, name='home'),
    path('historic/', views.historic_view, name='historic'),
    path('study/new/', views.create_study, name='create_study'),
    path('subject/new/', views.create_subject, name='create_subject'),
    path('study/delete/<int:id>/', views.delete_study, name='delete_study'),
    path(
        'subject/delete/<int:id>/', views.delete_subject, name='delete_subject'
    ),
    path('subject/<int:id>/', views.subject, name='subject'),
    path(
        'subject/update/<int:id>/', views.subject_update, name='subject_update'
    ),
    path('weekday/<str:weekday>/', views.weekday, name='weekday'),
]

studies/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Subject(models.Model):
    CHOICES = (
        ('blue', 'Azul'),
        ('orange', 'Laranja'),
        ('yellow', 'Amarelo'),
        ('red', 'Vermelho'),
        ('green', 'Verde'),
        ('pink', 'Rosa'),
        ('purple', 'Roxo'),
    )

    student = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=255)
    color = models.CharField(max_length=8, choices=CHOICES, default='azul')
    contents = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Study(models.Model):
    CHOICES = (
        ('Sunday', 'Domingo'),
        ('Monday', 'Segunda-feira'),
        ('Tuesday', 'Terça-feira'),
        ('Wednesday', 'Quarta-feira'),
        ('Thursday', 'Quinta-feira'),
        ('Friday', 'Sexta-feira'),
        ('Saturday', 'Sábado'),
    )

    weekday = models.CharField(max_length=9, choices=CHOICES)
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE, related_name='studies')
    start_time = models.TimeField(blank=True, null=True)
    end_time = models.TimeField(blank=True, null=True)

    def __str__(self):
        return f'{self.weekday} {self.subject}'


class Content(models.Model):
    name = models.CharField(max_length=255)
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE,
        related_name='content_list'
    )

    def __str__(self) -> str:
        return self.name


class Historic(models.Model):
    study = models.ForeignKey(Study, on_delete=models.CASCADE)
    contents_studied = models.ManyToManyField(Content)
    date = models.DateTimeField(auto_now=True)

studies/forms.py
from collections import defaultdict

from django import forms
from django.core.exceptions import ValidationError

from .models import Study, Subject


class StudyForm(forms.ModelForm):

    subject = forms.ModelChoiceField(
        label='Assunto',
        widget=forms.Select(
            attrs={
                'class': 'span-2'
            }
        ),
        queryset=None
    )

    class Meta:
        model = Study
        fields = (
            'weekday',
            'subject',
            'start_time',
            'end_time',
        )
        labels = {
            'weekday': 'Dia da semana',
            'start_time': 'Hora de início',
            'end_time': 'Hora de término',
        }
        widgets = {
            'weekday': forms.Select(
                attrs={
                    'class': 'span-2'
                }
            ),
            'start_time': forms.TimeInput(
                format='%H:%M',
                attrs={
                    'type': 'time',
                    'class': 'span-2'
                }
            ),
            'end_time': forms.TimeInput(
                format='%H:%M',
                attrs={
                    'type': 'time',
                    'class': 'span-2'
                }
            )
        }

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        subjects = Subject.objects.filter(student=user)
        self.fields['subject'].queryset = subjects

        self._my_errors = defaultdict(list)

    def clean(self):
        cleaned_data = super().clean()

        start_time = cleaned_data.get('start_time', None)
        end_time = cleaned_data.get('end_time', None)

        if end_time is not None and start_time is None:
            self._my_errors['start_time'].append(
                'Horário de termino precisa de um início')

        if self._my_errors:
            raise ValidationError(self._my_errors)

        return super().clean()


class SubjectForm(forms.ModelForm):

    class Meta:
        model = Subject
        fields = (
            'name',
            'contents',
            'color',
        )
        labels = {
            'name': 'Nome',
            'contents': 'Conteúdos',
            'color': 'Cor da tag'
        }
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'span-2',
                    'placeholder': 'Nome da matéria',
                }
            ),
            'contents': forms.Textarea(
                attrs={
                    'class': 'span-2',
                    'placeholder':
                    'Digite os conteúdos a serem estudados separados por -'
                }
            ),
            'color': forms.Select(
                attrs={
                    'class': 'subject-color span-2',
                    'type': 'color'
                }
            ),
        }
        help_texts = {
            'contents': 'Ex: Conteudo - Conteúdo 2 - Outro conteúdo'
        }

studies/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from utils.make_month import list_days_month

from .forms import StudyForm, SubjectForm
from .models import Historic, Study, Subject


@login_required(login_url='accounts:login', redirect_field_name='next')
def home(request):
    studies = Study.objects.filter(
        subject__student=request.user).order_by('start_time')
    subjects = Subject.objects.filter(student=request.user)

    studies_form_data = request.session.get('studies_form_data') or None
    subject_form_data = request.session.get('subject_form_data') or None

    form_study = StudyForm(request.user, studies_form_data)
    form_subject = SubjectForm(subject_form_data)

    return render(request, 'studies/pages/studies.html', context={
        'studies': studies,
        'subjects': subjects,
        'form_study': form_study,
        'form_subject': form_subject,
    })


@login_required(login_url='accounts:login', redirect_field_name='next')
def create_study(request):
    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session['studies_form_data'] = POST
    form = StudyForm(request.user, POST)

    if form.is_valid():
        form.save()
        del (request.session['studies_form_data'])
        messages.success(request, 'Estudo programado')
    else:
        messages.error(request, 'Erro no formulário')

    return redirect(reverse('studies:home'))


@login_required(login_url='accounts:login', redirect_field_name='next')
def create_subject(request):
    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session['subject_form_data'] = POST
    form = SubjectForm(request.POST)

    if form.is_valid():
        form_subject = form.save(commit=False)
        form_subject.student = request.user
        form_subject.save()

        del (request.session['subject_form_data'])
        messages.success(request, 'Assunto adicionado')
    else:
        messages.error(request, 'Erro no formulário')

    return redirect(reverse('studies:home'))


@login_required(login_url='accounts:login', redirect_field_name='next')
def delete_study(request, id):
    study = get_object_or_404(Study, subject__student=request.user, pk=id)

    study.delete()
    messages.warning(request, 'Estudo deletado')

    return redirect(reverse('studies:home'))


@login_required(login_url='accounts:login', redirect_field_name='next')
def delete_subject(request, id):
    subject = get_object_or_404(Subject, student=request.user, pk=id)

    subject.delete()
    messages.warning(request, 'Assunto deletado')

    return redirect(reverse('studies:home'))


@login_required(login_url='accounts:login', redirect_field_name='next')
def subject(request, id):
    subject = get_object_or_404(Subject, student=request.user, pk=id)
    form = SubjectForm(instance=subject)

    return render(request, 'studies/pages/subject.html', context={
        'subject': subject,
        'form': form
    })


def subject_update(request, id):
    if not request.POST:
        raise Http404()

    subject = get_object_or_404(Subject, student=request.user, pk=id)
    form = SubjectForm(request.POST, instance=subject)

    if form.is_valid():
        form.save()
        messages.success(request, 'Assunto editado')
    else:
        messages.error(request, 'Erro ao editar')

    return redirect(reverse('studies:subject', kwargs={'id': subject.id}))


@login_required(login_url='accounts:login', redirect_field_name='next')
def weekday(request, weekday):
    studies = Study.objects.filter(
        subject__student=request.user, weekday=weekday).order_by('start_time')
    subjects = Subject.objects.filter(student=request.user)

    return render(request, 'studies/pages/weekday.html', context={
        'studies': studies,
        'weekday': weekday,
        'subjects': subjects
    })


def historic_view(request):
    historics = Historic.objects.all()

    month = list_days_month()
    return render(request, 'studies/pages/historic.html', context={
        'month': month,
        'historics': historics
    })

studies/templates/studies/pages/historic.html
{% extends 'global/base.html' %}

{% block content %}
<section class="main-content">
    <h2 class="main-title">Histórico</h2>
    <article class="main-container-month">
        <div class="month-grid">
            <p>Domingo</p>
            <p>Segunda</p>
            <p>Terça</p>
            <p>Quarta</p>
            <p>Quinta</p>
            <p>Sexta</p>
            <p>Sabado</p>
            {% for weekday in month %}
                {% for day in weekday %}
                    <div class="day-content">
                        {% if day != 0 %}
                            <p class="day-title">{{ day }}</p>
                        {% endif %}
                        <ul>
                            {% for historic in historics %}
                                {% if historic.date.day == day %}
                                    <li class="weekday-subject {{ historic.study.subject.color }}">
                                        <div class="subject-content">
                                            <div class="subject-title">
                                                {{ historic.study.subject }}
                                            </div>
                                            
                                            {% for content in historic.contents_studied.all %}
                                                <p class="list-content">{{ content }}</p>
                                            {% endfor %}
                                        </div>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
    </article>
</section>
{% endblock content %}

studies/templates/studies/pages/studies.html
{% extends 'global/base.html' %}

{% block content %}
    <section class="main-content">
        <h2 class="main-title">Estudos</h2>

        {% include 'global/partials/messages.html' %}

        <article class="main-buttons">
            <div class="new-study">
                <label class="button open-modal" for="modal-new-study">
                    <span class="material-symbols-outlined add">add</span>
                    <p>Novo estudo</p>
                </label>
                <input type="checkbox" id="modal-new-study" class="checkbox-modal">
                <div class="modal">
                    <div class="content-modal">
                        <label for="modal-new-study" class="close-modal">
                            <span class="material-symbols-outlined cancel">
                                close
                            </span>
                        </label>
                        <div class="main-form">
                            <form action="{% url 'studies:create_study' %}" method="POST">
                                {% csrf_token %}
                                <div class="form-content form-content-grid">
                                    {% for field in form_study %}
                                    <div class="form-group {{ field.field.widget.attrs.class }}">
                                        {{ field.label_tag }}

                                        {{ field }}

                                        <p class="help-text">{{ field.help_text }}</p>
            
                                        {{ field.errors }}
                                    </div>
                                    {% endfor %}
                                    <div class="form-content form-content-grid">
                                        <div class="form-group">
                                            <button class="button-generic" type="submit">Adicionar</button>
                                        </div>
                                    </div>
                                </div> 
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="new-subject">
                <label class="button open-modal" for="modal-new-subject">
                    <span class="material-symbols-outlined add">add</span>
                    <p>Novo assunto</p>
                </label>
                <input type="checkbox" id="modal-new-subject" class="checkbox-modal">
                <div class="modal">
                    <div class="content-modal">
                        <label for="modal-new-subject" class="close-modal">
                            <span class="material-symbols-outlined cancel">
                                close
                            </span>
                        </label>
                        <div class="main-form">
                            <form action="{% url 'studies:create_subject' %}" method="POST">
                                {% csrf_token %}
                                <div class="form-content form-content-grid">
                                    {% for field in form_subject %}
                                    <div class="form-group {{ field.field.widget.attrs.class }}">
                                        {{ field.label_tag }}

                                        {{ field }}

                                        <p class="help-text">{{ field.help_text }}</p>
            
                                        {{ field.errors }}
                                    </div>
                                    {% endfor %}
                                    <div class="form-content form-content-grid">
                                        <div class="form-group">
                                            <button class="button-generic" type="submit">Adicionar</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </article>

        <article class="main-week-studies">
            <div class="weekday">
                <div class="weekday-title">
                    <h2>Domingo</h2>
                </div>
                <div class="weekday-content">
                    <ul>
                    {% for study in studies %}
                        {% if study.weekday == 'Sunday' %}

                            {% include 'studies/partials/subjects.html' %}

                        {% endif %}
                    {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="weekday">
                <div class="weekday-title">
                    <h2>Segunda</h2>
                </div>
                <div class="weekday-content">
                    <ul>
                    {% for study in studies %}
                        {% if study.weekday == 'Monday' %}

                            {% include 'studies/partials/subjects.html' %}

                        {% endif %}
                    {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="weekday">
                <div class="weekday-title">
                    <a href="{% url 'studies:weekday' 'Tuesday' %}">
                        <h2>Terça</h2>
                    </a>
                </div>
                <div class="weekday-content">
                    <ul>
                    {% for study in studies %}
                        {% if study.weekday == 'Tuesday' %}
                            
                            {% include 'studies/partials/subjects.html' %}

                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="weekday">
                <div class="weekday-title">
                    <a href="{% url 'studies:weekday' 'Wednesday' %}">
                        <h2>Quarta</h2>
                    </a>
                </div>
                <div class="weekday-content">
                    <ul>
                    {% for study in studies %}
                        {% if study.weekday == 'Wednesday' %}

                            {% include 'studies/partials/subjects.html' %}

                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="weekday">
                <div class="weekday-title">
                    <h2>Quinta</h2>
                </div>
                <div class="weekday-content">
                    <ul>
                    {% for study in studies %}
                        {% if study.weekday == 'Thursday' %}

                            {% include 'studies/partials/subjects.html' %}

                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="weekday">
                <div class="weekday-title">
                    <h2>Sexta</h2>
                </div>
                <div class="weekday-content">
                    <ul>
                    {% for study in studies %}
                        {% if study.weekday == 'Friday' %}

                            {% include 'studies/partials/subjects.html' %}

                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="weekday">
                <div class="weekday-title">
                    <h2>Sábado</h2>
                </div>
                <div class="weekday-content">
                    <ul>
                    {% for study in studies %}
                        {% if study.weekday == 'Saturday' %}

                            {% include 'studies/partials/subjects.html' %}

                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </article>

        <article class="main-subjects-list">
            <h3 class="main-title">Assuntos</h3>
            <div class="subjects-grid">
                <ul>
                    {% for subject in subjects %}
                    <a class="subject-link" href="{% url 'studies:subject' subject.id %}">
                        <li class="main-subject {{ subject.color }}">
                            <div class="subject-content">
                                <div class="subject-title">
                                    {{ subject.name }}
                                </div>
                            </div>
                            <form class="form-delete inline" action="{% url 'studies:delete_subject' subject.id %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="id-subject">
                
                                <button type="submit" class="link-danger plaintext-button"><span class="material-symbols-outlined">
                                delete
                                </span></button>
                            </form>
                        </li>
                    </a>
                    {% empty %}
                        <p class="center">Nenhum assunto encontrado. Adicione um novo assunto para começar a organizar seus estudos.</p>
                    {% endfor %}
                </ul>
            </div>
        </article>

    </section>

{% endblock content %}

studies/templates/studies/pages/subject.html
{% extends 'global/base.html' %}

{% block content %}
    <section class="main-content">
        <h2 class="main-title">{{ subject.name }}</h2>

        {% include 'global/partials/messages.html' %}

        <div class="main-form half-width">
            <form action="{% url 'studies:subject_update' subject.id %}" method="POST">
                {% csrf_token %}
                <div class="form-content form-content-grid">
                    {% for field in form %}
                    <div class="form-group {{ field.field.widget.attrs.class }}">
                        {{ field.label_tag }}

                        {{ field }}

                        <p class="help-text">{{ field.help_text }}</p>

                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    <div class="form-content form-content-grid">
                        <div class="form-group">
                            <button class="button-generic" type="submit">Editar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock content %}

studies/templates/studies/pages/weekday.html
{% extends 'global/base.html' %}

{% block content %}
<section class="main-content">
    <h2 class="main-title">{{ weekday }}</h2>
    <p class="sub-title center">Salve aqui seus estudos diários</p>
    <ul class="main-container-studies">
        {% for study in studies %}
            <li class="subjects-contents {{ study.subject.color }}">
                <div class="subject-content center">
                    <div class="subject-title">
                        {{ study.subject }}
                    </div>
                    
                    {% if study.start_time and study.end_time %}
                    <div class="subject-time">
                        {{ study.start_time }} - {{ study.end_time }}
                    </div>
                    {% elif study.start_time %}
                    <div class="subject-time">
                        {{ study.start_time }}
                    </div>
                    {% endif %}
                </div>
                {% if study.subject.content_list.all %}
                <div class="form-content">
                    {% for content in study.subject.content_list.all %}
                        <div class="content-item">
                            <label for="{{ content }}">
                                <input type="checkbox" name="{{ content }}" id="{{ content }}">
                                <span class="checkmark"></span>
                                {{ content }}
                            </label>
                        </div>
                    {% endfor %}
                </div>
                <div class="form-group center">
                    <button class="button-generic" type="submit">salvar</button>
                </div>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</section>
{% endblock content %}