accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout')
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('studies.urls')),
]

studies/urls.py
from django.urls import path

from . import views

app_name = 'studies'

urlpatterns = [
    path('', views.home, name='home'),
    path('historic/', views.historic_view, name='historic'),
    path('study/new/', views.create_study, name='create_study'),
    path('subject/new/', views.create_subject, name='create_subject'),
    path('study/delete/<int:id>/', views.delete_study, name='delete_study'),
    path(
        'subject/delete/<int:id>/', views.delete_subject, name='delete_subject'
    ),
    path('subject/<int:id>/', views.subject, name='subject'),
    path(
        'subject/update/<int:id>/', views.subject_update, name='subject_update'
    ),
    path('weekday/<str:weekday>/', views.weekday, name='weekday'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from collections import defaultdict

from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from utils.validators import email_is_valid, strong_password


class RegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._my_errors = defaultdict(list)

    username = forms.CharField(
        label='Usuário',
        error_messages={
            'required': 'Nome de usuário é obrigatório',
            'min_length': 'Use no mínimo 4 caracteres',
            'max_length': 'Use máximo 150 caracteres'
        },
        help_text=(
            'Obrigatório. Entre 4 e 150 caracteres. '
            'Letras, números e @/./+/-/_ apenas.'
        ),
        min_length=4, max_length=150
    )

    email = forms.CharField(
        label='E-mail',
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'exemplo@email.com'
            }
        ),
        required=False
    )

    first_name = forms.CharField(
        label='Nome',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ex: José'
            }
        ),
        required=False
    )

    last_name = forms.CharField(
        label='Sobrenome',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ex: Beto'
            }
        ),
        required=False
    )

    password = forms.CharField(
        label='Senha',
        widget=forms.PasswordInput(),
        error_messages={
            'required': 'Senha não pode ser vazia'
        },
        validators=[strong_password]
    )

    password2 = forms.CharField(
        label='Confirme a senha',
        widget=forms.PasswordInput(),
        error_messages={
            'required': 'Repita sua senha'
        }
    )

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password',
        ]

    def clean(self):
        cleaned_data = super().clean()

        password1 = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password1 != password2:
            self._my_errors['password'].append('Senhas diferentes')

        if self._my_errors:
            raise ValidationError(self._my_errors)

        return cleaned_data

    def clean_email(self):
        email = self.cleaned_data["email"]
        email_valid = email_is_valid(email)
        print(email_valid)

        if not email_valid:
            self._my_errors['email'].append('E-mail inválido')

        return email


class LoginForm(forms.Form):
    username = forms.CharField(
        label='Usuário',
        widget=forms.TextInput({
            'class': 'span-2',
            'placeholder': 'Digite seu usuário'
        })
    )
    password = forms.CharField(
        label='Senha',
        widget=forms.PasswordInput({
            'class': 'span-2',
            'placeholder': 'Digite sua senha'
        })
    )

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse

from .forms import LoginForm, RegisterForm


def register_view(request):
    register_form_data = request.session.get('register_form_data') or None
    form = RegisterForm(register_form_data)

    return render(request, 'accounts/pages/register.html', context={
        'form': form
    })


def register_create(request):
    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)

    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()

        messages.success(request, 'Cadastro sucedido')
        del (request.session['register_form_data'])
        return redirect(reverse('accounts:login'))

    messages.error(request, 'Erro no cadastro')
    return redirect(reverse('accounts:register'))


def login_view(request):
    form = LoginForm()

    return render(request, 'accounts/pages/login.html', context={
        'form': form
    })


def login_create(request):
    if not request.POST:
        raise Http404()

    form = LoginForm(request.POST)
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')

    if form.is_valid():
        authenticated_user = authenticate(
            username=username,
            password=password
        )

        if authenticated_user is not None:
            messages.success(request, 'Logado com sucesso')
            login(request, authenticated_user)
            return redirect(reverse('studies:home'))
        else:
            messages.error(request, 'Usuário ou senha inválido')

    else:
        messages.error(request, 'Credenciais inválidas')

    return redirect(reverse('accounts:login'))


@login_required(login_url='accounts:login', redirect_field_name='next')
def logout_view(request):
    messages.success(request, 'Logout sucedido')
    logout(request)
    return redirect(reverse('accounts:login'))

accounts/templates/accounts/pages/login.html
{% extends 'global/base.html' %}

{% block content %}
<section class="main-content">
        <h2 class="main-title">Entrar</h2>

        {% include 'global/partials/messages.html' %}

        {% if not user.is_authenticated %}
            <article class="main-login">
                <div class="main-form">
                    <form action="{% url 'accounts:login_create' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-content form-content-grid">
                            {% for field in form %}
                            <div class="form-group {{ field.field.widget.attrs.class }}">
                                {{ field.label_tag }}

                                {{ field }}

                                {{ field.errors }}
                            </div>
                            {% endfor %}
                            <div class="form-content form-content-grid">
                                <div class="form-group">
                                    <button class="button-generic" type="submit">Entrar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </article>
        {% else %}
            <div class="login-message">
                <p>O usuário {{ user.username }} já está logado! <a href="{% url 'studies:home' %}">Clique aqui</a> para voltar para home.</p>
            </div>
        {% endif %}
    </section>
{% endblock content %}

accounts/templates/accounts/pages/register.html
{% extends 'global/base.html' %}

{% block content %}
<section class="main-content">
    <h2 class="main-title">Registrar-se</h2>

    {% include 'global/partials/messages.html' %}

    <article class="main-register">
        <div class="main-form">
            <form action="{% url 'accounts:register_create' %}" method="POST">
                {% csrf_token %}
                <div class="form-content form-content-grid">
                    {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}

                        {{ field }}

                        <p class="help-text">{{ field.help_text }}</p>

                        {{ field.errors }}
                    </div>
                    {% endfor %}
                    <div class="form-content form-content-grid">
                        <div class="form-group">
                            <button class="button-generic" type="submit">Registrar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </article>
</section>
{% endblock content %}